package io.github.redisops.domain.validation;

public enum ValidationDifferenceType {
    MISSING_TARGET, EXTRA_TARGET, TYPE_DIFF, VALUE_DIFF, TTL_DIFF, LARGE_KEY_DEGRADED, UNVERIFIABLE_UNSUPPORTED_TYPE, UNVERIFIABLE_CONSUMER_GROUP, INCONCLUSIVE_CHANGED_DURING_READ
}
