CREATE TABLE platform_user (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 display_name VARCHAR(128) NOT NULL,
 status VARCHAR(16) NOT NULL,
 role VARCHAR(16) NULL,
 password_change_required BOOLEAN NOT NULL DEFAULT TRUE,
 version BIGINT NOT NULL DEFAULT 0,
 authorization_version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 last_login_at TIMESTAMP(3) NULL,
 INDEX idx_platform_user_status (status, id)
) ENGINE=InnoDB;
CREATE TABLE platform_identity (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT NOT NULL,
 source VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 provider VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
 subject VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
 identity_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 UNIQUE KEY uk_platform_identity (identity_digest),
 CONSTRAINT fk_identity_user FOREIGN KEY (user_id) REFERENCES platform_user(id)
) ENGINE=InnoDB;
CREATE TABLE platform_local_credential (
 user_id BIGINT NOT NULL PRIMARY KEY,
 login_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 password_hash VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 CONSTRAINT fk_local_credential_user FOREIGN KEY (user_id) REFERENCES platform_user(id)
) ENGINE=InnoDB;
CREATE TABLE platform_auth_control (
 id INT NOT NULL PRIMARY KEY,
 initialized BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE=InnoDB;
INSERT INTO platform_auth_control(id, initialized) VALUES (1, FALSE);
CREATE TABLE platform_login_limit (
 limit_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
 attempts INT NOT NULL,
 expires_at TIMESTAMP(3) NOT NULL,
 INDEX idx_login_limit_expiry (expires_at)
) ENGINE=InnoDB;
CREATE TABLE SPRING_SESSION (
 PRIMARY_ID CHAR(36) NOT NULL,
 SESSION_ID CHAR(36) NOT NULL,
 CREATION_TIME BIGINT NOT NULL,
 LAST_ACCESS_TIME BIGINT NOT NULL,
 MAX_INACTIVE_INTERVAL INT NOT NULL,
 EXPIRY_TIME BIGINT NOT NULL,
 PRINCIPAL_NAME VARCHAR(100),
 PRIMARY KEY (PRIMARY_ID),
 UNIQUE KEY SPRING_SESSION_IX1 (SESSION_ID),
 INDEX SPRING_SESSION_IX2 (EXPIRY_TIME),
 INDEX SPRING_SESSION_IX3 (PRINCIPAL_NAME)
) ENGINE=InnoDB;
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
 SESSION_PRIMARY_ID CHAR(36) NOT NULL,
 ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
 ATTRIBUTE_BYTES BLOB NOT NULL,
 PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
 CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
 REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB;
