import { useEffect,useState } from 'react'
import { Button,Form,Input,message,Modal,Popconfirm,Select,Space,Table,Tag } from 'antd'
import { DeleteOutlined,EditOutlined,LinkOutlined,PlusOutlined } from '@ant-design/icons'
import { api } from '../api.js'

export default function ApplicationsPage(){
  const [rows,setRows]=useState([]),[clusters,setClusters]=useState([]),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[binding,setBinding]=useState(null),[bindings,setBindings]=useState(null);const[form]=Form.useForm(),[bindForm]=Form.useForm()
  const load=async()=>{try{setRows(await api.applications());const c=await api.clusters({page:1,size:200});setClusters(c.items)}catch(e){message.error(e.message)}};useEffect(()=>{load()},[])
  const edit=row=>{setEditing(row||null);form.resetFields();form.setFieldsValue(row||{status:'ACTIVE'});setOpen(true)}
  const save=async()=>{try{const v=await form.validateFields();editing?await api.updateApplication(editing.id,editing.version,v):await api.createApplication(v);message.success('保存成功');setOpen(false);load()}catch(e){if(!e.errorFields)message.error(e.message)}}
  const remove=async r=>{try{await api.deleteApplication(r.id,r.version);message.success('已删除');load()}catch(e){message.error(e.message)}}
  const showBind=row=>{setBinding(row);bindForm.resetFields();bindForm.setFieldsValue({poolConfig:'{}'});setBinding(row)}
  const bind=async()=>{try{const v=await bindForm.validateFields();await api.bindApplication(binding.id,v.clusterId,{clientType:v.clientType,clientVersion:v.clientVersion,poolConfig:v.poolConfig});message.success('绑定成功');setBinding(null)}catch(e){if(!e.errorFields)message.error(e.message)}}
  const showBindings=async row=>{try{setBindings(await api.application(row.id))}catch(e){message.error(e.message)}}
  const unbind=async row=>{try{await api.unbindApplication(bindings.application.id,row.clusterId);message.success('已解绑');showBindings(bindings.application)}catch(e){message.error(e.message)}}
  const cols=[{title:'应用编码',dataIndex:'code'},{title:'应用名称',dataIndex:'name'},{title:'业务线',dataIndex:'businessLine'},{title:'负责人',dataIndex:'owner'},{title:'状态',dataIndex:'status',render:v=><Tag color={v==='ACTIVE'?'green':'default'}>{v}</Tag>},{title:'操作',render:(_,r)=><Space><Button icon={<LinkOutlined/>} onClick={()=>showBind(r)}>绑定集群</Button><Button onClick={()=>showBindings(r)}>绑定关系</Button><Button icon={<EditOutlined/>} onClick={()=>edit(r)}/><Popconfirm title="确认删除此应用？" onConfirm={()=>remove(r)}><Button danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}]
  return <><div className="toolbar"><div/><Button type="primary" icon={<PlusOutlined/>} onClick={()=>edit(null)}>新增应用</Button></div><Table rowKey="id" dataSource={rows} columns={cols}/>
    <Modal title={editing?'编辑应用':'新增应用'} open={open} onCancel={()=>setOpen(false)} onOk={save}><Form form={form} layout="vertical"><Form.Item name="code" label="应用编码" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="name" label="应用名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="businessLine" label="业务线"><Input/></Form.Item><Form.Item name="owner" label="负责人"><Input/></Form.Item><Form.Item name="status" label="状态"><Select options={['ACTIVE','INACTIVE'].map(value=>({value}))}/></Form.Item></Form></Modal>
    <Modal title={`绑定集群 · ${binding?.name||''}`} open={!!binding} onCancel={()=>setBinding(null)} onOk={bind}><Form form={bindForm} layout="vertical"><Form.Item name="clusterId" label="Redis 集群" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={clusters.map(c=>({value:c.id,label:`${c.name} (${c.environment})`}))}/></Form.Item><Form.Item name="clientType" label="客户端类型"><Input placeholder="Lettuce / Jedis / Redisson"/></Form.Item><Form.Item name="clientVersion" label="客户端版本"><Input/></Form.Item><Form.Item name="poolConfig" label="连接池配置 JSON"><Input.TextArea rows={4}/></Form.Item></Form></Modal>
    <Modal title={`绑定关系 · ${bindings?.application?.name||''}`} open={!!bindings} onCancel={()=>setBindings(null)} footer={null} width={720}><Table rowKey={r=>r.clusterId} pagination={false} dataSource={bindings?.bindings||[]} columns={[{title:'集群',dataIndex:'clusterId',render:id=>clusters.find(c=>c.id===id)?.name||id},{title:'客户端',dataIndex:'clientType'},{title:'版本',dataIndex:'clientVersion'},{title:'操作',render:(_,r)=><Popconfirm title="确认解绑？" onConfirm={()=>unbind(r)}><Button danger icon={<DeleteOutlined/>}>解绑</Button></Popconfirm>}]}/></Modal></>
}
