import GovernanceTaskDrawer from '../components/GovernanceTaskDrawer.jsx'
import GovernancePreflightActions from '../components/GovernancePreflightActions.jsx'
import {useCallback,useEffect,useMemo,useState} from 'react'
import {Alert,Button,Card,Form,Input,InputNumber,Modal,Select,Space,Table,Tag,message} from 'antd'
import {api} from '../api.js'

const colors={CREATED:'default',DRY_RUN_PAUSED:'orange',DRY_RUN:'processing',AWAITING_APPROVAL:'gold',APPROVED:'blue',RUNNING:'processing',PAUSED:'orange',COMPLETED:'success',CANCELLED:'default',FAILED:'error'}
const labels={CREATED:'待预检',DRY_RUN_PAUSED:'预检已暂停',DRY_RUN:'Dry Run 中',AWAITING_APPROVAL:'待审批',APPROVED:'已审批',RUNNING:'执行中',PAUSED:'已暂停',COMPLETED:'已完成',CANCELLED:'已取消',FAILED:'失败'}
const terminal=['COMPLETED','CANCELLED','FAILED']
export default function CleanupGovernancePage(){
  const [tasks,setTasks]=useState([]),[clusters,setClusters]=useState([]),[detail,setDetail]=useState(),[open,setOpen]=useState(false),[approval,setApproval]=useState(),[form]=Form.useForm(),[approvalForm]=Form.useForm()
  const selectedClusterId=Form.useWatch('clusterId',form),selectedCluster=useMemo(()=>clusters.find(x=>x.id===selectedClusterId),[clusters,selectedClusterId])
  const load=useCallback(async()=>{const [t,c]=await Promise.allSettled([api.cleanupGovernanceTasks(),api.clusters({size:200})]);if(t.status==='fulfilled')setTasks(t.value||[]);if(c.status==='fulfilled')setClusters(c.value.items||[])},[])
  const refresh=useCallback(async id=>{try{setDetail(await api.cleanupGovernanceTask(id))}catch(e){message.error(e.message)}},[])
  useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load])
  useEffect(()=>{const id=detail?.task?.id,status=detail?.task?.status;if(!id||terminal.includes(status)||status==='PAUSED')return;const timer=setInterval(()=>refresh(id),3000);return()=>clearInterval(timer)},[detail?.task?.id,detail?.task?.status,refresh])
  const act=async(fn,id)=>{try{await fn();message.success('操作已提交');await Promise.all([load(),refresh(id)])}catch(e){message.error(e.message)}}
  const actions=task=>{if(['CREATED','DRY_RUN','DRY_RUN_PAUSED','FAILED'].includes(task.status))return <GovernancePreflightActions task={task} kind="cleanup" onChanged={id=>Promise.all([load(),refresh(id)])}/>;if(task.status==='AWAITING_APPROVAL')return <Button size="small" type="primary" onClick={()=>{setApproval(task);}} >审批</Button>;if(task.status==='APPROVED')return <Button size="small" type="primary" onClick={()=>Modal.confirm({title:'确认开始删除数据？',content:'将重新扫描当前规则匹配的 Key 并执行 UNLINK，受影响上限约束。已删除数据不会自动恢复。',okText:'确认执行',cancelText:'取消',onOk:()=>act(()=>api.startCleanupGovernance(task.id,task.version),task.id)})}>开始执行</Button>;if(task.status==='RUNNING')return <Space><Button size="small" onClick={()=>act(()=>api.pauseCleanupGovernance(task.id,task.version),task.id)}>暂停</Button><Button danger size="small" onClick={()=>act(()=>api.cancelCleanupGovernance(task.id,task.version),task.id)}>取消</Button></Space>;if(task.status==='PAUSED')return <Space><Button size="small" type="primary" onClick={()=>act(()=>api.startCleanupGovernance(task.id,task.version),task.id)}>恢复</Button><Button danger size="small" onClick={()=>act(()=>api.cancelCleanupGovernance(task.id,task.version),task.id)}>取消</Button></Space>;return null}
  return <Space direction="vertical" size={16} style={{width:'100%'}}><Card title="数据清理治理" extra={<Button type="primary" onClick={()=>{form.resetFields();form.setFieldsValue({databaseNo:0,includePattern:'*',impactLimit:1000,scanRatePerSecond:200});setOpen(true)}}>新建清理任务</Button>}><Alert type="warning" showIcon message="高风险操作" description="清理执行 UNLINK。可预检后审批执行，或填写原因并确认跳过预检直接执行；删除后不可自动恢复。"/><Table style={{marginTop:16}} rowKey="id" dataSource={tasks} scroll={{x:1100}} columns={[{title:'任务',dataIndex:'taskNo'},{title:'集群',dataIndex:'clusterId',render:v=>clusters.find(x=>x.id===v)?.name||`#${v}`},{title:'范围',dataIndex:'includePattern'},{title:'影响上限',dataIndex:'impactLimit'},{title:'状态',dataIndex:'status',render:v=><Tag color={colors[v]}>{labels[v]||v}</Tag>},{title:'审批',dataIndex:'approvalStatus'},{title:'操作',render:(_,row)=><Button size="small" onClick={()=>refresh(row.id)}>详情</Button>}]} pagination={false}/></Card>
    <GovernanceTaskDrawer detail={detail} clusters={clusters} kind="cleanup" actions={actions} onClose={()=>setDetail(null)}/>
    <Modal open={open} title="新建数据清理任务" footer={null} onCancel={()=>setOpen(false)} destroyOnHidden><Form form={form} layout="vertical" onFinish={async values=>{try{await api.createCleanupGovernanceTask(values);message.success('任务已创建，可运行预检或明确跳过');setOpen(false);form.resetFields();load()}catch(e){message.error(e.message)}}}><Form.Item name="clusterId" label="集群" rules={[{required:true}]}><Select showSearch optionFilterProp="label" onChange={()=>form.setFieldValue('databaseNo',0)} options={clusters.map(x=>({value:x.id,label:`${x.name} · ${x.mode} · ${x.environment}`}))}/></Form.Item><Form.Item name="databaseNo" label="数据库"><InputNumber min={0} max={15} disabled={selectedCluster?.mode==='CLUSTER'} style={{width:'100%'}}/></Form.Item><Form.Item name="includePattern" label="Key Pattern" rules={[{required:true}]}><Input placeholder="例如 temp:*"/></Form.Item><Form.Item name="impactLimit" label="影响上限（Key 数）" rules={[{required:true}]}><InputNumber min={1} max={10000000} style={{width:'100%'}}/></Form.Item><Form.Item name="scanRatePerSecond" label="扫描/执行速率（Key/s）" rules={[{required:true}]}><InputNumber min={1} max={100000} style={{width:'100%'}}/></Form.Item><Alert type="info" showIcon message="创建阶段不会删除数据" description="可预检后审批执行，或填写原因并确认跳过预检直接执行。"/><Form.Item style={{margin:'16px 0 0',textAlign:'right'}}><Space><Button onClick={()=>setOpen(false)}>取消</Button><Button type="primary" htmlType="submit">创建任务</Button></Space></Form.Item></Form></Modal>
    <Modal open={!!approval} title="提交清理审批" onCancel={()=>setApproval(null)} onOk={async()=>{try{const note=await approvalForm.validateFields();await act(()=>api.approveCleanupGovernance(approval.id,approval.version,note.note),approval.id);setApproval(null);approvalForm.resetFields()}catch(e){message.error(e.message)}}}><Form form={approvalForm} layout="vertical"><Form.Item name="note" label="审批说明" rules={[{required:true,message:'请填写审批说明'}]}><Input.TextArea rows={4} placeholder="填写变更单号、业务确认和影响范围"/></Form.Item></Form></Modal>
  </Space>
}
