import { useEffect,useState } from 'react'
import { Alert,Button,Descriptions,Drawer,Form,Input,message,Modal,Popconfirm,Select,Space,Switch,Table,Tabs,Tag,Tooltip } from 'antd'
import { ApiOutlined,DeleteOutlined,EditOutlined,PlusOutlined,ReloadOutlined,SearchOutlined } from '@ant-design/icons'
import { api } from '../api.js'

const modes=['STANDALONE','SENTINEL','CLUSTER'],statuses=['ACTIVE','INACTIVE','UNREACHABLE']
export default function ClustersPage(){
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(false),[total,setTotal]=useState(0),[page,setPage]=useState(1)
  const [filters,setFilters]=useState({}),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[detail,setDetail]=useState(null)
  const [idcs,setIdcs]=useState([]),[connectionTesting,setConnectionTesting]=useState(false),[connectionResult,setConnectionResult]=useState(null);const [form]=Form.useForm();const authEnabled=Form.useWatch('authEnabled',form)
  const testedMode=Form.useWatch('mode',form),testedEndpoint=Form.useWatch('endpoint',form),testedUsername=Form.useWatch('username',form),testedPassword=Form.useWatch('password',form)
  const load=async(p=page)=>{setLoading(true);try{const data=await api.clusters({...filters,page:p,size:20});setRows(data.items);setTotal(data.total);setPage(p)}catch(e){message.error(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load(1);api.idcs().then(setIdcs).catch(()=>{})},[])
  useEffect(()=>{setConnectionResult(null)},[testedMode,testedEndpoint,authEnabled,testedUsername,testedPassword])
  const showCreate=()=>{setEditing(null);setConnectionResult(null);form.resetFields();form.setFieldsValue({mode:'CLUSTER',status:'ACTIVE',environment:'prod',authEnabled:false});setOpen(true)}
  const showEdit=async row=>{try{const value=await api.cluster(row.id);setEditing({...row,authEnabled:value.authentication.authEnabled});setConnectionResult(null);form.resetFields();form.setFieldsValue({...value.cluster,authEnabled:value.authentication.authEnabled,username:value.authentication.username,password:''});setOpen(true)}catch(e){message.error(e.message)}}
  const save=async()=>{try{const values=await form.validateFields();editing?await api.updateCluster(editing.id,editing.version,values):await api.createCluster(values);message.success('保存成功');setOpen(false);load()}catch(e){if(!e.errorFields)message.error(e.message)}}
  const testConnection=async()=>{setConnectionResult(null);try{await form.validateFields(['mode','endpoint','password']);const values=form.getFieldsValue(['mode','endpoint','authEnabled','username','password']);setConnectionTesting(true);const result=await api.testClusterConnection({...values,clusterId:editing?.id});setConnectionResult(result);message.success('Redis 配置校验和连通性测试通过')}catch(e){if(!e.errorFields)message.error(e.message)}finally{setConnectionTesting(false)}}
  const remove=async row=>{try{await api.deleteCluster(row.id,row.version);message.success('已删除');load()}catch(e){message.error(e.message)}}
  const getDetail=async id=>{const [value,discoveries]=await Promise.all([api.cluster(id),api.discoveries(id)]);return {...value,discoveries}}
  const showDetail=async row=>{try{setDetail(await getDetail(row.id))}catch(e){message.error(e.message)}}
  const discover=async()=>{try{const submission=await api.discover(detail.cluster.id);message.success('发现任务已提交');pollJob(submission.job.id,detail.cluster.id)}catch(e){message.error(e.message)}}
  const pollJob=(jobId,clusterId)=>{const timer=setInterval(async()=>{try{const job=await api.job(jobId);if(['SUCCEEDED','FAILED'].includes(job.status)){clearInterval(timer);setDetail(await getDetail(clusterId));job.status==='SUCCEEDED'?message.success('拓扑发现完成'):message.error(job.lastError||'拓扑发现失败')}}catch{clearInterval(timer)}},1200)}
  const location=id=>{const x=idcs.find(i=>i.id===id);return x?`${x.regionName} / ${x.name}`:'-'}
  const detailItems=detail?[{key:'name',label:'集群名称',children:detail.cluster.name},{key:'environment',label:'环境',children:detail.cluster.environment},{key:'mode',label:'部署模式',children:detail.cluster.mode},{key:'status',label:'状态',children:detail.cluster.status},{key:'endpoint',label:'Seed Endpoints',children:detail.cluster.endpoint},{key:'location',label:'Region / IDC',children:detail.location?`${detail.location.regionName} / ${detail.location.name}（${detail.location.regionCode} / ${detail.location.code}）`:'-'},{key:'auth',label:'连接认证',children:detail.authentication.authEnabled?<Space><Tag color="green">已启用</Tag><span>{detail.authentication.authType}{detail.authentication.username?` / ${detail.authentication.username}`:''}</span></Space>:<Tag>无认证</Tag>},{key:'password',label:'密码状态',children:detail.authentication.passwordConfigured?<Tag color="green">已配置</Tag>:<Tag>未配置</Tag>},{key:'businessLine',label:'业务线',children:detail.cluster.businessLine||'-'},{key:'owner',label:'业务负责人',children:detail.cluster.owner},{key:'opsOwner',label:'运维负责人',children:detail.cluster.opsOwner||'-'},{key:'serviceLevel',label:'服务等级',children:detail.cluster.serviceLevel||'-'},{key:'redisVersion',label:'Redis 版本',children:detail.cluster.redisVersion||'-'},{key:'version',label:'数据版本',children:detail.cluster.version},{key:'updatedAt',label:'更新时间',children:detail.cluster.updatedAt||'-'}]:[]
  const columns=[{title:'集群名称',dataIndex:'name',width:210,fixed:'left',ellipsis:true,render:(v,r)=><Tooltip title={v}><Button className="cluster-name-link" type="link" onClick={()=>showDetail(r)}>{v}</Button></Tooltip>},{title:'环境',dataIndex:'environment',width:100,ellipsis:true},{title:'模式',dataIndex:'mode',width:120},{title:'Endpoint',dataIndex:'endpoint',width:280,ellipsis:true,render:v=><Tooltip title={v}><span className="endpoint-cell">{v}</span></Tooltip>},{title:'机房',dataIndex:'idcId',width:210,ellipsis:true,render:id=><Tooltip title={location(id)}><span>{location(id)}</span></Tooltip>},{title:'业务线',dataIndex:'businessLine',width:120,ellipsis:true,render:v=>v||'-'},{title:'负责人',dataIndex:'owner',width:130,ellipsis:true},{title:'状态',dataIndex:'status',width:100,render:v=><Tag color={v==='ACTIVE'?'green':'default'}>{v}</Tag>},{title:'操作',width:96,fixed:'right',align:'center',render:(_,r)=><Space size={4}><Tooltip title="编辑"><Button type="text" icon={<EditOutlined/>} onClick={()=>showEdit(r)}/></Tooltip><Popconfirm title="确认删除此集群？" onConfirm={()=>remove(r)}><Tooltip title="删除"><Button type="text" danger icon={<DeleteOutlined/>}/></Tooltip></Popconfirm></Space>}]
  return <><div className="toolbar"><Space wrap><Input placeholder="环境" value={filters.environment} onChange={e=>setFilters({...filters,environment:e.target.value})}/><Input placeholder="业务线" value={filters.businessLine} onChange={e=>setFilters({...filters,businessLine:e.target.value})}/><Input placeholder="负责人" value={filters.owner} onChange={e=>setFilters({...filters,owner:e.target.value})}/><Button icon={<SearchOutlined/>} onClick={()=>load(1)}>查询</Button><Button icon={<ReloadOutlined/>} onClick={()=>{setFilters({});setTimeout(()=>load(1))}}>刷新</Button></Space><Button type="primary" icon={<PlusOutlined/>} onClick={showCreate}>新增集群</Button></div>
    <Table className="cluster-table" rowKey="id" size="middle" tableLayout="fixed" scroll={{x:1366}} loading={loading} columns={columns} dataSource={rows} pagination={{current:page,pageSize:20,total,showTotal:value=>`共 ${value} 个集群`,showSizeChanger:false,onChange:load}}/>
    <Modal title={editing?'编辑 Redis 集群':'新增 Redis 集群'} open={open} onCancel={()=>setOpen(false)} onOk={save} width={760} destroyOnHidden>
      <Form form={form} layout="vertical" className="form-grid"><Form.Item name="name" label="集群名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="environment" label="环境" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="mode" label="部署模式" rules={[{required:true}]}><Select options={modes.map(v=>({value:v}))}/></Form.Item><Form.Item name="endpoint" label="Seed Endpoints" extra="多个地址用英文逗号分隔；Sentinel 格式为 masterName@host1:26379,host2:26379" rules={[{required:true}]}><Input.TextArea rows={2} placeholder="host1:6379,host2:6379,host3:6379"/></Form.Item><Form.Item name="owner" label="业务负责人" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="opsOwner" label="运维负责人"><Input/></Form.Item><Form.Item name="businessLine" label="业务线"><Input/></Form.Item><Form.Item name="serviceLevel" label="服务等级"><Select allowClear options={['P1','P2','P3'].map(value=>({value}))}/></Form.Item><Form.Item name="redisVersion" label="Redis 版本"><Input/></Form.Item><Form.Item name="idcId" label="Region / IDC" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={idcs.filter(i=>i.status==='ACTIVE').map(i=>({value:i.id,label:`${i.regionName} / ${i.name}`}))}/></Form.Item><Form.Item name="status" label="状态"><Select options={statuses.map(v=>({value:v}))}/></Form.Item><div className={`auth-section ${authEnabled?'auth-section-enabled':''}`}><div className="auth-section-header"><div><div className="auth-section-title">连接认证</div><div className="auth-section-description">配置该集群统一使用的 Redis 连接账号</div></div><Form.Item name="authEnabled" valuePropName="checked" noStyle><Switch aria-label="启用认证" checkedChildren="已启用" unCheckedChildren="未启用"/></Form.Item></div>{editing?.authEnabled&&authEnabled===false&&<div className="auth-clear-warning">保存后将清除当前集群已配置的用户名和密码。</div>}{authEnabled?<div className="auth-fields"><Form.Item name="username" label="ACL 用户名（可选）" extra="留空时使用 requirepass/default 用户。"><Input autoComplete="off" placeholder="例如 redis-reader"/></Form.Item><Form.Item name="password" label="Redis 密码" extra={editing?.authEnabled?'密码已配置，留空表示保持不变。':'密码只写入加密存储，保存后不会回显。'} rules={[{validator:(_,value)=>!authEnabled||value||editing?.authEnabled?Promise.resolve():Promise.reject(new Error('请输入 Redis 密码'))}]}><Input.Password autoComplete="new-password" placeholder={editing?.authEnabled?'留空保持现有密码':'请输入 Redis 密码'}/></Form.Item></div>:<div className="auth-disabled-hint">当前按无认证 Redis 连接，适用于未配置 requirepass/ACL 的集群。</div>}</div></Form>
      <div className="connection-test-section">
        <div><div className="connection-test-title">配置校验与连通性</div><div className="auth-section-description">测试 Endpoint、部署模式、认证信息及拓扑命令权限，测试结果不会保存。</div></div>
        <Button icon={<ApiOutlined/>} loading={connectionTesting} onClick={testConnection}>测试连通性</Button>
        {connectionResult&&<Alert className="connection-test-result" type="success" showIcon message={`连接成功 · 发现 ${connectionResult.discoveredNodeCount} 个节点 · ${connectionResult.elapsedMillis} ms`}/>}
      </div>
    </Modal>
    <Drawer title={detail?.cluster?.name} width={850} open={!!detail} onClose={()=>setDetail(null)} extra={<Button type="primary" onClick={discover}>发现拓扑</Button>}>
      {detail&&<><Descriptions bordered size="small" column={2} items={detailItems}/><Tabs className="detail-tabs" items={[
        {key:'nodes',label:`节点 (${detail.nodes.length})`,children:<Table size="small" rowKey="id" pagination={false} dataSource={detail.nodes} columns={[{title:'地址',render:(_,r)=>`${r.host}:${r.port}`},{title:'角色',dataIndex:'role'},{title:'状态',dataIndex:'status'},{title:'Slots',dataIndex:'slotRanges'}]}/>},
        {key:'bindings',label:`应用绑定 (${detail.bindings.length})`,children:<Table size="small" rowKey={r=>`${r.applicationId}-${r.clusterId}`} pagination={false} dataSource={detail.bindings} columns={[{title:'Application ID',dataIndex:'applicationId'},{title:'客户端',dataIndex:'clientType'},{title:'版本',dataIndex:'clientVersion'},{title:'连接池',dataIndex:'poolConfig'}]}/>},
        {key:'history',label:`发现历史 (${detail.discoveries.length})`,children:<Table size="small" rowKey="id" pagination={false} dataSource={detail.discoveries} columns={[{title:'Run ID',dataIndex:'id'},{title:'状态',dataIndex:'status'},{title:'节点数',dataIndex:'nodeCount'},{title:'开始时间',dataIndex:'startedAt'},{title:'结束时间',dataIndex:'finishedAt'},{title:'错误',dataIndex:'errorMessage'}]}/>} ]}/></>}
    </Drawer></>
}
