import { useEffect,useState } from 'react'
import { Button,Form,Input,message,Modal,Popconfirm,Select,Space,Table,Tabs,Tag } from 'antd'
import { DeleteOutlined,EditOutlined,PlusOutlined } from '@ant-design/icons'
import { api } from '../api.js'

export default function LocationsPage(){
  const [regions,setRegions]=useState([]),[idcs,setIdcs]=useState([]),[kind,setKind]=useState('region'),[editing,setEditing]=useState(null),[open,setOpen]=useState(false);const[form]=Form.useForm()
  const load=async()=>{try{const[r,i]=await Promise.all([api.regions(),api.idcs()]);setRegions(r);setIdcs(i)}catch(e){message.error(e.message)}};useEffect(()=>{load()},[])
  const edit=(type,row)=>{setKind(type);setEditing(row||null);form.resetFields();form.setFieldsValue(row||{status:'ACTIVE'});setOpen(true)}
  const save=async()=>{try{const v=await form.validateFields();if(kind==='region')editing?await api.updateRegion(editing.id,editing.version,v):await api.createRegion(v);else editing?await api.updateIdc(editing.id,editing.version,v):await api.createIdc(v);message.success('保存成功');setOpen(false);load()}catch(e){if(!e.errorFields)message.error(e.message)}}
  const remove=async(type,row)=>{try{type==='region'?await api.deleteRegion(row.id,row.version):await api.deleteIdc(row.id,row.version);message.success('已删除');load()}catch(e){message.error(e.message)}}
  const actions=type=>({title:'操作',render:(_,r)=><Space><Button icon={<EditOutlined/>} onClick={()=>edit(type,r)}/><Popconfirm title="确认删除？" onConfirm={()=>remove(type,r)}><Button danger icon={<DeleteOutlined/>}/></Popconfirm></Space>})
  const regionTable=<><div className="toolbar"><div/><Button type="primary" icon={<PlusOutlined/>} onClick={()=>edit('region')}>新增 Region</Button></div><Table rowKey="id" dataSource={regions} columns={[{title:'编码',dataIndex:'code'},{title:'名称',dataIndex:'name'},{title:'状态',dataIndex:'status',render:v=><Tag color={v==='ACTIVE'?'green':'default'}>{v}</Tag>},{title:'描述',dataIndex:'description'},actions('region')]}/></>
  const idcTable=<><div className="toolbar"><div/><Button type="primary" icon={<PlusOutlined/>} onClick={()=>edit('idc')}>新增 IDC</Button></div><Table rowKey="id" dataSource={idcs} columns={[{title:'Region',render:(_,r)=>`${r.regionName} (${r.regionCode})`},{title:'IDC 编码',dataIndex:'code'},{title:'IDC 名称',dataIndex:'name'},{title:'网络域',dataIndex:'networkDomain'},{title:'状态',dataIndex:'status',render:v=><Tag color={v==='ACTIVE'?'green':'default'}>{v}</Tag>},actions('idc')]}/></>
  return <><Tabs items={[{key:'regions',label:'Region',children:regionTable},{key:'idcs',label:'IDC',children:idcTable}]}/><Modal title={`${editing?'编辑':'新增'} ${kind==='region'?'Region':'IDC'}`} open={open} onCancel={()=>setOpen(false)} onOk={save}><Form form={form} layout="vertical"><Form.Item name="code" label="稳定编码" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="name" label="显示名称" rules={[{required:true}]}><Input/></Form.Item>{kind==='idc'&&<><Form.Item name="regionId" label="所属 Region" rules={[{required:true}]}><Select options={regions.filter(r=>r.status==='ACTIVE').map(r=>({value:r.id,label:`${r.name} (${r.code})`}))}/></Form.Item><Form.Item name="networkDomain" label="网络域"><Input/></Form.Item></>}<Form.Item name="status" label="状态"><Select options={['ACTIVE','INACTIVE'].map(value=>({value}))}/></Form.Item><Form.Item name="description" label="描述"><Input.TextArea/></Form.Item></Form></Modal></>
}
