import { useEffect,useState } from 'react'
import { Button,Descriptions,Drawer,Form,Input,InputNumber,message,Modal,Popconfirm,Select,Space,Table,Tag } from 'antd'
import { DeleteOutlined,EditOutlined,PlusOutlined,SwapOutlined } from '@ant-design/icons'
import { api } from '../api.js'

export default function RelationsPage(){
  const [rows,setRows]=useState([]),[clusters,setClusters]=useState([]),[idcs,setIdcs]=useState([]),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[detail,setDetail]=useState(null);const[form]=Form.useForm()
  const load=async()=>{try{const[r,c,i]=await Promise.all([api.relations(),api.clusters({page:1,size:200}),api.idcs()]);setRows(r);setClusters(c.items);setIdcs(i)}catch(e){message.error(e.message)}};useEffect(()=>{load()},[])
  const name=id=>clusters.find(c=>c.id===id)?.name||id
  const clusterLabel=id=>{const c=clusters.find(x=>x.id===id),i=idcs.find(x=>x.id===c?.idcId);return c?`${c.name}（${i?`${i.regionName} / ${i.name}`:'未配置机房'}）`:id}
  const edit=row=>{setEditing(row||null);form.resetFields();form.setFieldsValue(row||{relationType:'DISASTER_RECOVERY',status:'ACTIVE',desiredRpoSeconds:30});setOpen(true)}
  const save=async()=>{try{const v=await form.validateFields();editing?await api.updateRelation(editing.id,editing.version,v):await api.createRelation(v);message.success('保存成功');setOpen(false);load()}catch(e){if(!e.errorFields)message.error(e.message)}}
  const remove=async r=>{try{await api.deleteRelation(r.id,r.version);message.success('已删除');load()}catch(e){message.error(e.message)}}
  const show=async r=>{try{setDetail(await api.relation(r.id))}catch(e){message.error(e.message)}}
  const start=async()=>{try{await api.startSwitchover(detail.relation.id);message.success('旧方向已停止，请完成外部流量切换后确认');setDetail(await api.relation(detail.relation.id));load()}catch(e){message.error(e.message)}}
  const finish=async(sw,action)=>{try{action==='confirm'?await api.confirmSwitchover(sw.id,sw.version):await api.cancelSwitchover(sw.id,sw.version);message.success(action==='confirm'?'已确认并创建反向任务':'已取消并恢复原方向');setDetail(await api.relation(detail.relation.id));load()}catch(e){message.error(e.message)}}
  const columns=[{title:'关系名称',dataIndex:'name',render:(v,r)=><Button type="link" onClick={()=>show(r)}>{v}</Button>},{title:'主集群',dataIndex:'primaryClusterId',render:name},{title:'备集群',dataIndex:'standbyClusterId',render:name},{title:'方向',render:(_,r)=>`${name(r.primaryClusterId)} → ${name(r.standbyClusterId)}`},{title:'目标 RPO',dataIndex:'desiredRpoSeconds',render:v=>`${v}s`},{title:'状态',dataIndex:'status',render:v=><Tag color={v==='ACTIVE'?'green':v==='SWITCHING'?'orange':'default'}>{v}</Tag>},{title:'操作',render:(_,r)=><Space><Button icon={<EditOutlined/>} onClick={()=>edit(r)}/><Popconfirm title="确认删除关系？" onConfirm={()=>remove(r)}><Button danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}]
  return <><div className="toolbar"><div/><Button type="primary" icon={<PlusOutlined/>} onClick={()=>edit(null)}>新增主备关系</Button></div><Table rowKey="id" dataSource={rows} columns={columns}/><Modal title={editing?'编辑主备关系':'新增主备关系'} open={open} onCancel={()=>setOpen(false)} onOk={save}><Form form={form} layout="vertical"><Form.Item name="name" label="关系名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="relationType" label="关系类型"><Select options={[{value:'DISASTER_RECOVERY'}]}/></Form.Item><Form.Item name="primaryClusterId" label="主集群" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={clusters.map(c=>({value:c.id,label:clusterLabel(c.id)}))}/></Form.Item><Form.Item name="standbyClusterId" label="备集群" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={clusters.map(c=>({value:c.id,label:clusterLabel(c.id)}))}/></Form.Item><Form.Item name="desiredRpoSeconds" label="目标 RPO（秒）" rules={[{required:true}]}><InputNumber min={1} style={{width:'100%'}}/></Form.Item>{editing&&<Form.Item name="status" label="状态"><Select options={['ACTIVE','PAUSED','FAILED'].map(value=>({value}))}/></Form.Item>}<Form.Item name="description" label="描述"><Input.TextArea/></Form.Item></Form></Modal>
    <Drawer title={detail?.relation?.name} width={900} open={!!detail} onClose={()=>setDetail(null)} extra={<Button icon={<SwapOutlined/>} disabled={detail?.relation?.status!=='ACTIVE'} onClick={start}>发起主备切换</Button>}>{detail&&<><Descriptions bordered column={2} items={[{key:'direction',label:'当前方向',children:`${name(detail.relation.primaryClusterId)} → ${name(detail.relation.standbyClusterId)}`},{key:'status',label:'状态',children:detail.relation.status},{key:'rpo',label:'目标 RPO',children:`${detail.relation.desiredRpoSeconds}s`},{key:'type',label:'类型',children:detail.relation.relationType}]}/><h3>同步任务</h3><Table size="small" rowKey="id" pagination={false} dataSource={detail.tasks} columns={[{title:'任务号',dataIndex:'taskNo'},{title:'方向',render:(_,r)=>`${name(r.sourceClusterId)} → ${name(r.targetClusterId)}`},{title:'状态',dataIndex:'status'},{title:'RPO',dataIndex:'lastRpoSeconds'}]}/><h3>切换记录</h3><Table size="small" rowKey="id" pagination={false} dataSource={detail.switchovers} columns={[{title:'ID',dataIndex:'id'},{title:'状态',dataIndex:'status'},{title:'发起人',dataIndex:'operator'},{title:'操作',render:(_,r)=>r.status==='WAITING_EXTERNAL_SWITCH'?<Space><Popconfirm title="确认外部业务流量已经切换？" onConfirm={()=>finish(r,'confirm')}><Button type="primary">确认切换</Button></Popconfirm><Button onClick={()=>finish(r,'cancel')}>取消</Button></Space>:'-'}]}/></>}</Drawer></>
}
