import { useEffect, useState } from 'react'
import { Button, Descriptions, Drawer, Form, InputNumber, Modal, Select, Space, Table, Tag, message } from 'antd'
import { PlusOutlined, PlayCircleOutlined } from '@ant-design/icons'
import { api } from '../api.js'

const statusColor = { CREATED: 'default', CHECKING: 'processing', READY: 'cyan', RUNNING: 'processing', PASSED: 'success', FAILED: 'error', INCONCLUSIVE: 'warning', CANCELLED: 'default' }
const differenceColor = { MISSING_TARGET: 'error', EXTRA_TARGET: 'error', TYPE_DIFF: 'error', VALUE_DIFF: 'error', TTL_DIFF: 'warning', LARGE_KEY_DEGRADED: 'gold', UNVERIFIABLE_UNSUPPORTED_TYPE: 'gold', INCONCLUSIVE_CHANGED_DURING_READ: 'default' }
const defaultValues = { strictness: 'REPORT', samplingMode: 'COUNT', sampleLimit: 1000, samplePercentage: 10, ttlToleranceSeconds: 5, largeKeyThresholdBytes: 67108864, maxDeepCompareBytes: 8388608, chunkBytes: 1048576, maxElementsPerKey: 100000, sourceDb: 0, targetDb: 0 }
const bytes = value => value == null ? '-' : value >= 1024 * 1024 ? `${(value / 1024 / 1024).toFixed(1)} MiB` : `${value} B`
const samplingLabel = task => task.samplingMode === 'FULL' ? '全量校验' : task.samplingMode === 'PERCENTAGE' ? `${task.samplePercentage}% 抽样` : `${task.sampleLimit} Key 抽样`

export default function ValidationTasksPage() {
  const [rows, setRows] = useState([]); const [clusters, setClusters] = useState([]); const [open, setOpen] = useState(false); const [detail, setDetail] = useState(null); const [differences, setDifferences] = useState({ items: [], total: 0, page: 1, size: 20 }); const [form] = Form.useForm()
  const sourceClusterId = Form.useWatch('sourceClusterId', form); const targetClusterId = Form.useWatch('targetClusterId', form); const samplingMode = Form.useWatch('samplingMode', form)
  const sourceNeedsDb = ['STANDALONE', 'SENTINEL'].includes(clusters.find(cluster => cluster.id === sourceClusterId)?.mode); const targetNeedsDb = ['STANDALONE', 'SENTINEL'].includes(clusters.find(cluster => cluster.id === targetClusterId)?.mode)
  const clusterOptions = clusters.map(cluster => ({ value: cluster.id, label: `${cluster.name} · ${cluster.idcName || cluster.idcCode || '未设置 IDC'} · ${cluster.mode}` }))
  const load = async () => { try { const tasks = await api.validationTasks(); const enriched = await Promise.all(tasks.map(async task => ({ ...task, latestRun: (await api.validationTask(task.id)).latestRun }))); setRows(enriched) } catch (error) { message.error(error.message) } }
  useEffect(() => { load(); api.clusters().then(result => setClusters(result.items || result)); const id = new URLSearchParams(window.location.hash.split('?')[1] || '').get('syncTaskId'); if (id) api.syncTask(id).then(result => { form.setFieldsValue({ ...defaultValues, syncTaskId: result.task.id, sourceClusterId: result.task.sourceClusterId, targetClusterId: result.task.targetClusterId, sourceDb: result.task.sourceDb, targetDb: result.task.targetDb }); setOpen(true) }).catch(error => message.error(`无法读取同步任务：${error.message}`)); const timer = window.setInterval(() => load(), 2000); return () => window.clearInterval(timer) }, [])
  const show = id => Promise.all([api.validationTask(id), api.validationDifferences(id)]).then(([task, diffs]) => { setDetail(task); setDifferences(diffs) }).catch(error => message.error(error.message))
  useEffect(() => { if (!detail || !['CHECKING', 'RUNNING'].includes(detail.task.status)) return undefined; const timer = window.setInterval(() => show(detail.task.id), 2000); return () => window.clearInterval(timer) }, [detail?.task?.id, detail?.task?.status])
  const create = async () => { try { await api.createValidationTask(await form.validateFields()); message.success('校验任务已创建'); setOpen(false); form.resetFields(); load() } catch (error) { if (!error?.errorFields) message.error(error.message) } }
  return <><Space style={{ marginBottom: 16 }}><Button type="primary" icon={<PlusOutlined />} onClick={() => { form.resetFields(); form.setFieldsValue(defaultValues); setOpen(true) }}>新建数据校验</Button><span className="muted">全量校验遍历全部符合过滤条件的 Key；大 Key 仍受安全阈值保护。</span></Space>
    <Table rowKey="id" dataSource={rows} onRow={row => ({ onClick: () => show(row.id) })} columns={[{ title: '任务编号', dataIndex: 'taskNo' }, { title: '来源', render: (_, row) => row.syncTaskId ? `同步任务 #${row.syncTaskId}` : '独立校验' }, { title: '源 / 目标', render: (_, row) => `${row.sourceClusterId} → ${row.targetClusterId}` }, { title: '覆盖范围', render: (_, row) => samplingLabel(row) }, { title: '进度', render: (_, row) => row.latestRun ? `${row.latestRun.comparedKeys} / ${row.latestRun.plannedKeys} 已比较 · ${row.latestRun.differenceCount} 差异` : '-' }, { title: '模式', dataIndex: 'strictness', render: value => <Tag color={value === 'STRICT' ? 'purple' : 'blue'}>{value === 'STRICT' ? '严格门禁' : '报告'}</Tag> }, { title: '状态', dataIndex: 'status', render: value => <Tag color={statusColor[value]}>{value}</Tag> }, { title: '操作', render: (_, row) => <Space onClick={event => event.stopPropagation()}>{['CREATED', 'READY', 'FAILED', 'INCONCLUSIVE'].includes(row.status) && <Button size="small" icon={<PlayCircleOutlined />} onClick={async () => { try { await api.startValidationTask(row.id, row.version); message.success('已提交校验'); load() } catch (error) { message.error(error.message) } }}>开始</Button>}{!['PASSED', 'CANCELLED'].includes(row.status) && <Button size="small" danger onClick={async () => { try { await api.cancelValidationTask(row.id, row.version); load() } catch (error) { message.error(error.message) } }}>取消</Button>}</Space> }]} />
    <Modal open={open} title="新建数据校验" width={620} okText="创建" onOk={create} onCancel={() => setOpen(false)}><Form form={form} layout="vertical" initialValues={defaultValues}><Form.Item name="syncTaskId" hidden><InputNumber /></Form.Item><Form.Item name="sourceClusterId" label="源集群" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={clusterOptions} /></Form.Item><Form.Item name="targetClusterId" label="目标集群" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={clusterOptions} /></Form.Item>{sourceNeedsDb && <Form.Item name="sourceDb" label="源 DB" rules={[{ required: true }]}><InputNumber min={0} style={{ width: '100%' }} /></Form.Item>}{targetNeedsDb && <Form.Item name="targetDb" label="目标 DB" rules={[{ required: true }]}><InputNumber min={0} style={{ width: '100%' }} /></Form.Item>}<Form.Item name="samplingMode" label="校验范围"><Select options={[{ value: 'COUNT', label: '固定数量抽样' }, { value: 'PERCENTAGE', label: '百分比抽样（稳定哈希筛选）' }, { value: 'FULL', label: '全量校验（遍历全部 Key）' }]} /></Form.Item>{samplingMode === 'COUNT' && <Form.Item name="sampleLimit" label="抽样 Key 数" rules={[{ required: true }]}><InputNumber min={1} max={1000000} style={{ width: '100%' }} /></Form.Item>}{samplingMode === 'PERCENTAGE' && <Form.Item name="samplePercentage" label="抽样比例" rules={[{ required: true }]} extra="同一任务重试会选中同一批 Key"><InputNumber min={0.01} max={100} step={0.01} addonAfter="%" style={{ width: '100%' }} /></Form.Item>}<Form.Item name="strictness" label="校验结论"><Select options={[{ value: 'REPORT', label: '报告模式：大 Key 仅报告风险' }, { value: 'STRICT', label: '严格门禁：大 Key 或未验证项不自动通过' }]} /></Form.Item><Form.Item name="largeKeyThresholdBytes" label="大 Key 阈值（Bytes）"><InputNumber min={1} style={{ width: '100%' }} /></Form.Item><Form.Item name="maxDeepCompareBytes" label="最大深度比较大小（Bytes）"><InputNumber min={1} style={{ width: '100%' }} /></Form.Item></Form></Modal>
    <Drawer width={760} open={!!detail} title="校验结果" onClose={() => setDetail(null)}>{detail && <><Descriptions bordered size="small" column={2}><Descriptions.Item label="状态"><Tag color={statusColor[detail.task.status]}>{detail.task.status}</Tag></Descriptions.Item><Descriptions.Item label="覆盖范围">{samplingLabel(detail.task)}</Descriptions.Item><Descriptions.Item label="待比对 Key">{detail.latestRun?.plannedKeys ?? '-'}</Descriptions.Item><Descriptions.Item label="已扫描">{detail.latestRun?.scannedKeys ?? '-'}</Descriptions.Item><Descriptions.Item label="已比较">{detail.latestRun?.comparedKeys ?? '-'} / {detail.latestRun?.plannedKeys ?? '-'}</Descriptions.Item><Descriptions.Item label="降级大 Key">{detail.latestRun?.degradedCount ?? '-'}</Descriptions.Item><Descriptions.Item label="未确定">{detail.latestRun?.inconclusiveCount ?? '-'}</Descriptions.Item></Descriptions><h3 style={{ marginTop: 20 }}>差异与风险</h3><Table size="small" rowKey="id" dataSource={differences.items} pagination={{ current: differences.page, pageSize: differences.size, total: differences.total, onChange: (page, size) => api.validationDifferences(detail.task.id, page, size).then(setDifferences) }} columns={[{ title: '类型', dataIndex: 'differenceType', render: value => <Tag color={differenceColor[value]}>{value}</Tag> }, { title: 'Key', dataIndex: 'keyName', render: value => value || '历史记录仅保留摘要' }, { title: 'Redis 类型', dataIndex: 'redisType' }, { title: '源大小', dataIndex: 'sourceSize', render: bytes }, { title: '目标大小', dataIndex: 'targetSize', render: bytes }, { title: '原因', dataIndex: 'degradedReason' }]} /></>}</Drawer>
  </>
}
