import {useCallback,useEffect,useMemo,useState} from 'react'
import {Alert,Button,Card,Descriptions,Form,Input,InputNumber,Modal,Progress,Select,Space,Statistic,Table,Tag,message} from 'antd'
import {api} from '../api.js'

const colors={CREATED:'default',DRY_RUN:'processing',AWAITING_APPROVAL:'gold',APPROVED:'blue',RUNNING:'processing',PAUSED:'orange',COMPLETED:'success',CANCELLED:'default',FAILED:'error'}
const labels={CREATED:'待 Dry Run',DRY_RUN:'Dry Run 中',AWAITING_APPROVAL:'待审批',APPROVED:'已审批',RUNNING:'执行中',PAUSED:'已暂停',COMPLETED:'已完成',CANCELLED:'已取消',FAILED:'失败'}
const terminal=['COMPLETED','CANCELLED','FAILED']
export default function CleanupGovernancePage(){
  const [tasks,setTasks]=useState([]),[clusters,setClusters]=useState([]),[detail,setDetail]=useState(),[open,setOpen]=useState(false),[approval,setApproval]=useState(),[form]=Form.useForm(),[approvalForm]=Form.useForm()
  const selectedClusterId=Form.useWatch('clusterId',form),selectedCluster=useMemo(()=>clusters.find(x=>x.id===selectedClusterId),[clusters,selectedClusterId])
  const load=useCallback(async()=>{const [t,c]=await Promise.allSettled([api.cleanupGovernanceTasks(),api.clusters({size:200})]);if(t.status==='fulfilled')setTasks(t.value||[]);if(c.status==='fulfilled')setClusters(c.value.items||[])},[])
  const refresh=useCallback(async id=>{try{setDetail(await api.cleanupGovernanceTask(id))}catch(e){message.error(e.message)}},[])
  useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load])
  useEffect(()=>{const id=detail?.task?.id,status=detail?.task?.status;if(!id||terminal.includes(status)||status==='PAUSED')return;const timer=setInterval(()=>refresh(id),3000);return()=>clearInterval(timer)},[detail?.task?.id,detail?.task?.status,refresh])
  const act=async(fn,id)=>{try{await fn();message.success('操作已提交');await Promise.all([load(),refresh(id)])}catch(e){message.error(e.message)}}
  const actions=task=>{if(task.status==='CREATED')return <Button size="small" onClick={()=>act(()=>api.dryRunCleanupGovernance(task.id,task.version),task.id)}>Dry Run</Button>;if(task.status==='AWAITING_APPROVAL')return <Button size="small" type="primary" onClick={()=>{setApproval(task);}} >审批</Button>;if(task.status==='APPROVED')return <Button size="small" type="primary" onClick={()=>Modal.confirm({title:'确认开始删除数据？',content:'将对 Dry Run 命中的 Key 执行 UNLINK，已删除数据不会自动恢复。',okText:'确认执行',cancelText:'取消',onOk:()=>act(()=>api.startCleanupGovernance(task.id,task.version),task.id)})}>开始执行</Button>;if(task.status==='RUNNING')return <Space><Button size="small" onClick={()=>act(()=>api.pauseCleanupGovernance(task.id,task.version),task.id)}>暂停</Button><Button danger size="small" onClick={()=>act(()=>api.cancelCleanupGovernance(task.id,task.version),task.id)}>取消</Button></Space>;if(task.status==='PAUSED')return <Space><Button size="small" type="primary" onClick={()=>act(()=>api.startCleanupGovernance(task.id,task.version),task.id)}>恢复</Button><Button danger size="small" onClick={()=>act(()=>api.cancelCleanupGovernance(task.id,task.version),task.id)}>取消</Button></Space>;return null}
  const run=detail?.latestRun,progress=run?.plannedKeys?Math.min(100,run.scannedKeys/run.plannedKeys*100):0
  return <Space direction="vertical" size={16} style={{width:'100%'}}><Card title="数据清理治理" extra={<Button type="primary" onClick={()=>{form.resetFields();form.setFieldsValue({databaseNo:0,includePattern:'*',impactLimit:1000,scanRatePerSecond:200});setOpen(true)}}>新建清理任务</Button>}><Alert type="warning" showIcon message="高风险操作" description="清理只允许执行 UNLINK。必须先 Dry Run、提交审批说明，再人工确认执行；平台不提供自动恢复。"/><Table style={{marginTop:16}} rowKey="id" dataSource={tasks} scroll={{x:1100}} columns={[{title:'任务',dataIndex:'taskNo'},{title:'集群',dataIndex:'clusterId',render:v=>clusters.find(x=>x.id===v)?.name||`#${v}`},{title:'范围',dataIndex:'includePattern'},{title:'影响上限',dataIndex:'impactLimit'},{title:'状态',dataIndex:'status',render:v=><Tag color={colors[v]}>{labels[v]||v}</Tag>},{title:'审批',dataIndex:'approvalStatus'},{title:'操作',render:(_,row)=><Space><Button size="small" onClick={()=>refresh(row.id)}>详情</Button>{actions(row)}</Space>}]} pagination={false}/></Card>
    {detail&&<Card title={`${detail.task.taskNo} 详情`} extra={<Button onClick={()=>setDetail(null)}>关闭</Button>}><Descriptions bordered size="small" column={{xs:1,sm:2,lg:4}}><Descriptions.Item label="状态"><Tag color={colors[detail.task.status]}>{labels[detail.task.status]||detail.task.status}</Tag></Descriptions.Item><Descriptions.Item label="审批说明">{detail.task.approvalNote||'-'}</Descriptions.Item><Descriptions.Item label="Key 范围">{detail.task.includePattern}</Descriptions.Item><Descriptions.Item label="影响上限">{detail.task.impactLimit}</Descriptions.Item></Descriptions>{run&&<><Space wrap size={24} style={{marginTop:20}}><Statistic title="扫描" value={run.scannedKeys} suffix={`/ ${run.plannedKeys}`}/><Statistic title="候选 Key" value={run.candidateKeys}/><Statistic title="已 UNLINK" value={run.deletedKeys}/><Statistic title="跳过" value={run.skippedKeys}/><Statistic title="失败" value={run.failedKeys}/></Space><Progress style={{marginTop:16}} percent={Number(progress.toFixed(1))} status={run.status==='FAILED'?'exception':run.status==='COMPLETED'?'success':'active'}/><Table style={{marginTop:16}} size="small" rowKey="shardId" pagination={false} dataSource={detail.checkpoints} columns={[{title:'分片',dataIndex:'shardId'},{title:'Cursor',dataIndex:'cursor'},{title:'已扫描',dataIndex:'scannedKeys'},{title:'状态',dataIndex:'status'}]}/></>}</Card>}
    <Modal open={open} title="新建数据清理任务" footer={null} onCancel={()=>setOpen(false)} destroyOnClose><Form form={form} layout="vertical" onFinish={async values=>{try{await api.createCleanupGovernanceTask(values);message.success('任务已创建，请先执行 Dry Run');setOpen(false);form.resetFields();load()}catch(e){message.error(e.message)}}}><Form.Item name="clusterId" label="集群" rules={[{required:true}]}><Select showSearch optionFilterProp="label" onChange={()=>form.setFieldValue('databaseNo',0)} options={clusters.map(x=>({value:x.id,label:`${x.name} · ${x.mode} · ${x.environment}`}))}/></Form.Item><Form.Item name="databaseNo" label="数据库"><InputNumber min={0} max={15} disabled={selectedCluster?.mode==='CLUSTER'} style={{width:'100%'}}/></Form.Item><Form.Item name="includePattern" label="Key Pattern" rules={[{required:true}]}><Input placeholder="例如 temp:*"/></Form.Item><Form.Item name="impactLimit" label="影响上限（Key 数）" rules={[{required:true}]}><InputNumber min={1} max={10000000} style={{width:'100%'}}/></Form.Item><Form.Item name="scanRatePerSecond" label="扫描/执行速率（Key/s）" rules={[{required:true}]}><InputNumber min={1} max={100000} style={{width:'100%'}}/></Form.Item><Alert type="info" showIcon message="创建阶段不会删除数据" description="Dry Run 完成后必须填写审批说明，审批通过后才能开始执行。"/><Form.Item style={{margin:'16px 0 0',textAlign:'right'}}><Space><Button onClick={()=>setOpen(false)}>取消</Button><Button type="primary" htmlType="submit">创建任务</Button></Space></Form.Item></Form></Modal>
    <Modal open={!!approval} title="提交清理审批" onCancel={()=>setApproval(null)} onOk={async()=>{try{const note=await approvalForm.validateFields();await act(()=>api.approveCleanupGovernance(approval.id,approval.version,note.note),approval.id);setApproval(null);approvalForm.resetFields()}catch(e){message.error(e.message)}}}><Form form={approvalForm} layout="vertical"><Form.Item name="note" label="审批说明" rules={[{required:true,message:'请填写审批说明'}]}><Input.TextArea rows={4} placeholder="填写变更单号、业务确认和影响范围"/></Form.Item></Form></Modal>
  </Space>
}
