import { useEffect,useState } from 'react'
import { Button,Drawer,Form,Input,InputNumber,message,Modal,Select,Space,Table,Tag } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { api } from '../api.js'

const next={CREATED:['CHECKING','CANCELLED'],CHECKING:['READY','FAILED','CANCELLED'],READY:['FULL_SYNCING','CANCELLED'],FULL_SYNCING:['INCR_SYNCING','PAUSED','FAILED','CANCELLED'],INCR_SYNCING:['CAUGHT_UP','PAUSED','FAILED','CANCELLED'],CAUGHT_UP:['FINISHED','PAUSED','FAILED','CANCELLED'],PAUSED:['FULL_SYNCING','INCR_SYNCING','CAUGHT_UP','CANCELLED'],FAILED:['CHECKING','CANCELLED']}
export default function SyncTasksPage(){
  const [rows,setRows]=useState([]),[relations,setRelations]=useState([]),[clusters,setClusters]=useState([]),[idcs,setIdcs]=useState([]),[open,setOpen]=useState(false),[moving,setMoving]=useState(null),[detail,setDetail]=useState(null);const[form]=Form.useForm(),[moveForm]=Form.useForm()
  const relationId=Form.useWatch('relationId',form),selectedRelation=relations.find(r=>r.id===relationId)
  const load=async()=>{try{const[t,r,c,i]=await Promise.all([api.syncTasks(),api.relations(),api.clusters({page:1,size:200}),api.idcs()]);setRows(t);setRelations(r);setClusters(c.items);setIdcs(i)}catch(e){message.error(e.message)}};useEffect(()=>{load()},[])
  const name=id=>clusters.find(c=>c.id===id)?.name||id
  const clusterLabel=id=>{const c=clusters.find(x=>x.id===id),i=idcs.find(x=>x.id===c?.idcId);return c?`${c.name}（${i?`${i.regionName} / ${i.name}`:'未配置机房'}）`:id}
  const create=async()=>{try{const v=await form.validateFields();if(v.relationId){delete v.sourceClusterId;delete v.targetClusterId;v.purpose='DISASTER_RECOVERY'}await api.createSyncTask(v);message.success('任务已创建');setOpen(false);load()}catch(e){if(!e.errorFields)message.error(e.message)}}
  const move=row=>{setMoving(row);setTimeout(()=>{moveForm.resetFields();moveForm.setFieldsValue({targetStatus:next[row.status]?.[0]})})}
  const transition=async()=>{try{const v=await moveForm.validateFields();await api.transitionSyncTask(moving.id,moving.version,v);message.success('状态已更新');setMoving(null);load()}catch(e){if(!e.errorFields)message.error(e.message)}}
  const show=async row=>{try{setDetail(await api.syncTask(row.id))}catch(e){message.error(e.message)}}
  const columns=[{title:'任务号',dataIndex:'taskNo',render:(v,r)=><Button type="link" onClick={()=>show(r)}>{v}</Button>},{title:'类型',dataIndex:'purpose'},{title:'关系',dataIndex:'relationId',render:id=>relations.find(r=>r.id===id)?.name||'-'},{title:'方向',render:(_,r)=>`${name(r.sourceClusterId)} → ${name(r.targetClusterId)}`},{title:'状态',dataIndex:'status',render:v=><Tag color={v==='CAUGHT_UP'?'green':v==='FAILED'?'red':'blue'}>{v}</Tag>},{title:'RPO',dataIndex:'lastRpoSeconds',render:v=>v==null?'-':`${v}s`},{title:'操作',render:(_,r)=><Button disabled={!next[r.status]?.length} onClick={()=>move(r)}>推进状态</Button>}]
  return <><div className="toolbar"><div className="muted">状态推进接口供同步工具适配器及联调使用</div><Button type="primary" icon={<PlusOutlined/>} onClick={()=>{form.resetFields();form.setFieldsValue({purpose:'ADHOC',syncMode:'FULL_AND_INCREMENTAL'});setOpen(true)}}>新增同步任务</Button></div><Table rowKey="id" dataSource={rows} columns={columns}/><Modal title="新增同步任务" open={open} onCancel={()=>setOpen(false)} onOk={create}><Form form={form} layout="vertical"><Form.Item name="relationId" label="长期主备关系（可选）"><Select allowClear onChange={value=>value&&form.setFieldsValue({sourceClusterId:undefined,targetClusterId:undefined,purpose:'DISASTER_RECOVERY'})} options={relations.filter(r=>r.status==='ACTIVE').map(r=>({value:r.id,label:r.name}))}/></Form.Item>{selectedRelation?<Form.Item label="同步方向" extra="源和目标由主备关系确定，无需重复选择"><Input readOnly value={`${clusterLabel(selectedRelation.primaryClusterId)} → ${clusterLabel(selectedRelation.standbyClusterId)}`}/></Form.Item>:<><Form.Item name="sourceClusterId" label="临时任务源集群" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={clusters.map(c=>({value:c.id,label:clusterLabel(c.id)}))}/></Form.Item><Form.Item name="targetClusterId" label="临时任务目标集群" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={clusters.map(c=>({value:c.id,label:clusterLabel(c.id)}))}/></Form.Item><Form.Item name="purpose" label="任务用途" rules={[{required:true}]}><Select options={['MIGRATION','ADHOC'].map(value=>({value}))}/></Form.Item></>}<Form.Item name="syncMode" label="同步模式" rules={[{required:true}]}><Select options={['FULL_AND_INCREMENTAL','INCREMENTAL'].map(value=>({value}))}/></Form.Item><Form.Item name="toolType" label="同步工具"><Input placeholder="后续适配器类型，可暂不填"/></Form.Item></Form></Modal><Modal title={`推进任务 · ${moving?.taskNo||''}`} open={!!moving} onCancel={()=>setMoving(null)} onOk={transition}><Form form={moveForm} layout="vertical"><Form.Item name="targetStatus" label="目标状态" rules={[{required:true}]}><Select options={(next[moving?.status]||[]).map(value=>({value}))}/></Form.Item><Form.Item noStyle shouldUpdate={(a,b)=>a.targetStatus!==b.targetStatus}>{({getFieldValue})=>getFieldValue('targetStatus')==='CAUGHT_UP'&&<Form.Item name="lastRpoSeconds" label="当前 RPO（秒）" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item>}</Form.Item><Form.Item name="message" label="事件说明"><Input/></Form.Item></Form></Modal><Drawer title={detail?.task?.taskNo} open={!!detail} width={720} onClose={()=>setDetail(null)}><Table rowKey="id" pagination={false} dataSource={detail?.events||[]} columns={[{title:'时间',dataIndex:'createdAt'},{title:'原状态',dataIndex:'fromStatus'},{title:'新状态',dataIndex:'toStatus'},{title:'操作人',dataIndex:'operator'},{title:'说明',dataIndex:'message'}]}/></Drawer></>
}
