package io.github.redisops.application.sync;

import io.github.redisops.application.relation.ClusterRelationService;
import io.github.redisops.common.BusinessException;
import io.github.redisops.domain.audit.AuditRepository;
import io.github.redisops.domain.relation.*;
import io.github.redisops.domain.sync.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.*;

@Service
public class SyncService {
    private final SyncRepository sync;private final ClusterRelationRepository relations;private final ClusterRelationService relationService;private final AuditRepository audits;
    public SyncService(SyncRepository sync,ClusterRelationRepository relations,ClusterRelationService relationService,AuditRepository audits){this.sync=sync;this.relations=relations;this.relationService=relationService;this.audits=audits;}
    @Transactional public SyncTask create(Long relationId,Long sourceId,Long targetId,SyncPurpose purpose,SyncMode mode,String tool,String operator){
        long source,target;SyncPurpose actualPurpose;
        if(relationId!=null){var relation=relationService.get(relationId);if(relation.status()!=RelationStatus.ACTIVE)throw invalid("relation must be active");source=relation.primaryClusterId();target=relation.standbyClusterId();actualPurpose=SyncPurpose.DISASTER_RECOVERY;}
        else {if(sourceId==null||targetId==null)throw invalid("sourceClusterId and targetClusterId are required without relationId");source=sourceId;target=targetId;actualPurpose=purpose==null?SyncPurpose.ADHOC:purpose;}
        relationService.validatePair(source,target);var task=newTask(relationId,source,target,actualPurpose,mode,tool);var saved=sync.saveTask(task,operator,"sync task created");audit(operator,"SYNC_TASK_CREATE","SYNC_TASK",saved.id());return saved;}
    public SyncTask get(long id){return sync.findTask(id).orElseThrow(()->BusinessException.notFound("sync task",id));}
    public List<SyncTask> list(Long relationId){if(relationId!=null)relationService.get(relationId);return sync.findTasks(relationId);}
    public List<SyncTaskEvent> events(long id){get(id);return sync.findEvents(id);}
    @Transactional public SyncTask transition(long id,long version,SyncTaskStatus target,Long rpo,String error,String message,String operator){var old=get(id);if(!old.status().canTransitionTo(target))throw invalid("illegal sync task transition: "+old.status()+" -> "+target);if(target==SyncTaskStatus.CAUGHT_UP){if(rpo==null||rpo<0)throw invalid("lastRpoSeconds is required when caught up");if(old.relationId()!=null&&rpo>relationService.get(old.relationId()).desiredRpoSeconds())throw invalid("RPO exceeds relation target");}var x=new SyncTask(old.id(),old.taskNo(),old.relationId(),old.sourceClusterId(),old.targetClusterId(),old.purpose(),old.syncMode(),target,old.toolType(),rpo==null?old.lastRpoSeconds():rpo,error,version,old.createdAt(),Instant.now(),target.terminal()?Instant.now():null);if(!sync.updateTask(x,version,operator,message))concurrent();audit(operator,"SYNC_TASK_TRANSITION","SYNC_TASK",id);return get(id);}
    @Transactional public Switchover startSwitchover(long relationId,String operator){var relation=relationService.get(relationId);if(relation.status()!=RelationStatus.ACTIVE)throw invalid("relation must be active");if(sync.countActiveSwitchovers(relationId)>0)throw inUse("relation already has an active switchover");var task=sync.findLatestTask(relationId).orElseThrow(()->invalid("relation has no sync task"));if(task.status()!=SyncTaskStatus.CAUGHT_UP)throw invalid("latest sync task must be CAUGHT_UP");if(task.lastRpoSeconds()==null||task.lastRpoSeconds()>relation.desiredRpoSeconds())throw invalid("latest task does not meet target RPO");var stopped=new SyncTask(task.id(),task.taskNo(),task.relationId(),task.sourceClusterId(),task.targetClusterId(),task.purpose(),task.syncMode(),SyncTaskStatus.FINISHED,task.toolType(),task.lastRpoSeconds(),null,task.version(),task.createdAt(),Instant.now(),Instant.now());if(!sync.updateTask(stopped,task.version(),operator,"stopped for switchover"))concurrent();var switching=new ClusterRelation(relation.id(),relation.name(),relation.relationType(),relation.primaryClusterId(),relation.standbyClusterId(),RelationStatus.SWITCHING,relation.desiredRpoSeconds(),relation.description(),relation.version(),relation.createdAt(),Instant.now());if(!relations.update(switching,relation.version()))concurrent();var result=sync.saveSwitchover(new Switchover(null,relationId,relation.primaryClusterId(),relation.standbyClusterId(),task.id(),null,SwitchoverStatus.WAITING_EXTERNAL_SWITCH,operator,null,0,Instant.now(),Instant.now(),null));audit(operator,"SWITCHOVER_START","SWITCHOVER",result.id());return result;}
    public Switchover getSwitchover(long id){return sync.findSwitchover(id).orElseThrow(()->BusinessException.notFound("switchover",id));}
    public List<Switchover> switchovers(long relationId){relationService.get(relationId);return sync.findSwitchovers(relationId);}
    @Transactional public Switchover confirm(long id,long version,String operator){var sw=getSwitchover(id);waiting(sw);var relation=relationService.get(sw.relationId());if(relation.status()!=RelationStatus.SWITCHING||relation.primaryClusterId()!=sw.oldPrimaryClusterId()||relation.standbyClusterId()!=sw.oldStandbyClusterId())throw invalid("relation direction changed unexpectedly");var swapped=new ClusterRelation(relation.id(),relation.name(),relation.relationType(),relation.standbyClusterId(),relation.primaryClusterId(),RelationStatus.ACTIVE,relation.desiredRpoSeconds(),relation.description(),relation.version(),relation.createdAt(),Instant.now());if(!relations.update(swapped,relation.version()))concurrent();var reverse=sync.saveTask(newTask(relation.id(),relation.standbyClusterId(),relation.primaryClusterId(),SyncPurpose.DISASTER_RECOVERY,SyncMode.FULL_AND_INCREMENTAL,null),operator,"reverse task created after external traffic switch");var done=new Switchover(sw.id(),sw.relationId(),sw.oldPrimaryClusterId(),sw.oldStandbyClusterId(),sw.stoppedTaskId(),reverse.id(),SwitchoverStatus.CONFIRMED,sw.operator(),null,version,sw.createdAt(),Instant.now(),Instant.now());if(!sync.updateSwitchover(done,version))concurrent();audit(operator,"SWITCHOVER_CONFIRM","SWITCHOVER",id);return getSwitchover(id);}
    @Transactional public Switchover cancel(long id,long version,String operator){var sw=getSwitchover(id);waiting(sw);var relation=relationService.get(sw.relationId());var restored=new ClusterRelation(relation.id(),relation.name(),relation.relationType(),sw.oldPrimaryClusterId(),sw.oldStandbyClusterId(),RelationStatus.ACTIVE,relation.desiredRpoSeconds(),relation.description(),relation.version(),relation.createdAt(),Instant.now());if(!relations.update(restored,relation.version()))concurrent();var task=sync.saveTask(newTask(relation.id(),sw.oldPrimaryClusterId(),sw.oldStandbyClusterId(),SyncPurpose.DISASTER_RECOVERY,SyncMode.FULL_AND_INCREMENTAL,null),operator,"original direction restored after switchover cancellation");var cancelled=new Switchover(sw.id(),sw.relationId(),sw.oldPrimaryClusterId(),sw.oldStandbyClusterId(),sw.stoppedTaskId(),task.id(),SwitchoverStatus.CANCELLED,sw.operator(),null,version,sw.createdAt(),Instant.now(),null);if(!sync.updateSwitchover(cancelled,version))concurrent();audit(operator,"SWITCHOVER_CANCEL","SWITCHOVER",id);return getSwitchover(id);}
    private static SyncTask newTask(Long relationId,long source,long target,SyncPurpose purpose,SyncMode mode,String tool){var now=Instant.now();return new SyncTask(null,"SYNC-"+UUID.randomUUID().toString().replace("-","").substring(0,20).toUpperCase(),relationId,source,target,purpose,mode==null?SyncMode.FULL_AND_INCREMENTAL:mode,SyncTaskStatus.CREATED,tool,null,null,0,now,now,null);}
    private static void waiting(Switchover x){if(x.status()!=SwitchoverStatus.WAITING_EXTERNAL_SWITCH)throw invalid("switchover is not waiting for external switch");}
    private void audit(String op,String action,String type,long id){audits.append(op,action,type,Long.toString(id),"SUCCESS");}
    private static BusinessException invalid(String m){return new BusinessException("INVALID_ARGUMENT",m);}private static BusinessException inUse(String m){return new BusinessException("RESOURCE_IN_USE",m);}private static void concurrent(){throw new BusinessException("CONCURRENT_MODIFICATION","resource was modified, reload and retry");}
}
