port 26379
protected-mode no
dir /tmp
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor phase1-master redis-sentinel-master 6379 1
sentinel down-after-milliseconds phase1-master 5000
sentinel failover-timeout phase1-master 10000
sentinel parallel-syncs phase1-master 1
